### ISSUE TITLE
Support stable compilers

### ISSUE THREAD

**Issue by Xaeroxe** [Jakobeha/winit-modular#1]
This crate uses two nightly features

```rust
#![feature(drain_filter)]
#![feature(box_into_inner)]
```

`drain_filter` is a nice convenience function but ultimately provides no new capabilities. Also the function isn't called anywhere in the crate currently.

`box_into_inner` can be removed because dereferencing a box automatically moves out the contents. `Box::into_inner(x)` is equivalent to the stable `*x`.

**Comment by Jakobeha** [comment]
Ok, I've removed feature requirements so it should compile on stable now
